robot:
  _target_: gello.robots.xarm_robot.XArmRobot
  ip: "192.168.1.226"
  real: true

agent:
  _target_: gello.agents.gello_agent.GelloAgent
  port: "/dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTA7NNMG-if00-port0"
  dynamixel_config:
    _target_: gello.agents.gello_agent.DynamixelRobotConfig
    joint_ids: [1, 2, 3, 4, 5, 6, 7]
    joint_offsets: [
      1.5708,
      3.1416,
      6.2832,
      3.1416,
      4.7124,
      1.5708,
      3.1416
    ]
    joint_signs: [1, 1, 1, 1, 1, 1, 1]
    gripper_config: [8, 196, 155]
  start_joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

hz: 30
